spring:
    web:
        resources:
            add-mappings: false

server:
    servlet:
        session:
            cookie:
                same-site: strict

logging:
    level:
        org.springframework.web.servlet.PageNotFound: off
